// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/compound/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateCompoundSetting struct {
	Delegator        string              `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	ValidatorSetting []*ValidatorSetting `protobuf:"bytes,2,rep,name=validatorSetting,proto3" json:"validatorSetting,omitempty"`
	AmountToRemain   types.Coin          `protobuf:"bytes,3,opt,name=amountToRemain,proto3" json:"amountToRemain"`
	Frequency        int32               `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
}

func (m *MsgCreateCompoundSetting) Reset()         { *m = MsgCreateCompoundSetting{} }
func (m *MsgCreateCompoundSetting) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCompoundSetting) ProtoMessage()    {}
func (*MsgCreateCompoundSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_20f31f02f49b9fd9, []int{0}
}
func (m *MsgCreateCompoundSetting) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCompoundSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCompoundSetting.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCompoundSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCompoundSetting.Merge(m, src)
}
func (m *MsgCreateCompoundSetting) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCompoundSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCompoundSetting.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCompoundSetting proto.InternalMessageInfo

func (m *MsgCreateCompoundSetting) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgCreateCompoundSetting) GetValidatorSetting() []*ValidatorSetting {
	if m != nil {
		return m.ValidatorSetting
	}
	return nil
}

func (m *MsgCreateCompoundSetting) GetAmountToRemain() types.Coin {
	if m != nil {
		return m.AmountToRemain
	}
	return types.Coin{}
}

func (m *MsgCreateCompoundSetting) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

type MsgCreateCompoundSettingResponse struct {
}

func (m *MsgCreateCompoundSettingResponse) Reset()         { *m = MsgCreateCompoundSettingResponse{} }
func (m *MsgCreateCompoundSettingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCompoundSettingResponse) ProtoMessage()    {}
func (*MsgCreateCompoundSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20f31f02f49b9fd9, []int{1}
}
func (m *MsgCreateCompoundSettingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCompoundSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCompoundSettingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCompoundSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCompoundSettingResponse.Merge(m, src)
}
func (m *MsgCreateCompoundSettingResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCompoundSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCompoundSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCompoundSettingResponse proto.InternalMessageInfo

type MsgUpdateCompoundSetting struct {
	Delegator        string              `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
	ValidatorSetting []*ValidatorSetting `protobuf:"bytes,2,rep,name=validatorSetting,proto3" json:"validatorSetting,omitempty"`
	AmountToRemain   types.Coin          `protobuf:"bytes,3,opt,name=amountToRemain,proto3" json:"amountToRemain"`
	Frequency        int32               `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
}

func (m *MsgUpdateCompoundSetting) Reset()         { *m = MsgUpdateCompoundSetting{} }
func (m *MsgUpdateCompoundSetting) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCompoundSetting) ProtoMessage()    {}
func (*MsgUpdateCompoundSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_20f31f02f49b9fd9, []int{2}
}
func (m *MsgUpdateCompoundSetting) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCompoundSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCompoundSetting.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCompoundSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCompoundSetting.Merge(m, src)
}
func (m *MsgUpdateCompoundSetting) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCompoundSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCompoundSetting.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCompoundSetting proto.InternalMessageInfo

func (m *MsgUpdateCompoundSetting) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

func (m *MsgUpdateCompoundSetting) GetValidatorSetting() []*ValidatorSetting {
	if m != nil {
		return m.ValidatorSetting
	}
	return nil
}

func (m *MsgUpdateCompoundSetting) GetAmountToRemain() types.Coin {
	if m != nil {
		return m.AmountToRemain
	}
	return types.Coin{}
}

func (m *MsgUpdateCompoundSetting) GetFrequency() int32 {
	if m != nil {
		return m.Frequency
	}
	return 0
}

type MsgUpdateCompoundSettingResponse struct {
}

func (m *MsgUpdateCompoundSettingResponse) Reset()         { *m = MsgUpdateCompoundSettingResponse{} }
func (m *MsgUpdateCompoundSettingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCompoundSettingResponse) ProtoMessage()    {}
func (*MsgUpdateCompoundSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20f31f02f49b9fd9, []int{3}
}
func (m *MsgUpdateCompoundSettingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCompoundSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCompoundSettingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCompoundSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCompoundSettingResponse.Merge(m, src)
}
func (m *MsgUpdateCompoundSettingResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCompoundSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCompoundSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCompoundSettingResponse proto.InternalMessageInfo

type MsgDeleteCompoundSetting struct {
	Delegator string `protobuf:"bytes,1,opt,name=delegator,proto3" json:"delegator,omitempty"`
}

func (m *MsgDeleteCompoundSetting) Reset()         { *m = MsgDeleteCompoundSetting{} }
func (m *MsgDeleteCompoundSetting) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCompoundSetting) ProtoMessage()    {}
func (*MsgDeleteCompoundSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_20f31f02f49b9fd9, []int{4}
}
func (m *MsgDeleteCompoundSetting) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCompoundSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCompoundSetting.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCompoundSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCompoundSetting.Merge(m, src)
}
func (m *MsgDeleteCompoundSetting) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCompoundSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCompoundSetting.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCompoundSetting proto.InternalMessageInfo

func (m *MsgDeleteCompoundSetting) GetDelegator() string {
	if m != nil {
		return m.Delegator
	}
	return ""
}

type MsgDeleteCompoundSettingResponse struct {
}

func (m *MsgDeleteCompoundSettingResponse) Reset()         { *m = MsgDeleteCompoundSettingResponse{} }
func (m *MsgDeleteCompoundSettingResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCompoundSettingResponse) ProtoMessage()    {}
func (*MsgDeleteCompoundSettingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_20f31f02f49b9fd9, []int{5}
}
func (m *MsgDeleteCompoundSettingResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCompoundSettingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCompoundSettingResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCompoundSettingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCompoundSettingResponse.Merge(m, src)
}
func (m *MsgDeleteCompoundSettingResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCompoundSettingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCompoundSettingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCompoundSettingResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateCompoundSetting)(nil), "temporal.compound.MsgCreateCompoundSetting")
	proto.RegisterType((*MsgCreateCompoundSettingResponse)(nil), "temporal.compound.MsgCreateCompoundSettingResponse")
	proto.RegisterType((*MsgUpdateCompoundSetting)(nil), "temporal.compound.MsgUpdateCompoundSetting")
	proto.RegisterType((*MsgUpdateCompoundSettingResponse)(nil), "temporal.compound.MsgUpdateCompoundSettingResponse")
	proto.RegisterType((*MsgDeleteCompoundSetting)(nil), "temporal.compound.MsgDeleteCompoundSetting")
	proto.RegisterType((*MsgDeleteCompoundSettingResponse)(nil), "temporal.compound.MsgDeleteCompoundSettingResponse")
}

func init() { proto.RegisterFile("temporal/compound/tx.proto", fileDescriptor_20f31f02f49b9fd9) }

var fileDescriptor_20f31f02f49b9fd9 = []byte{
	// 408 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x54, 0xcf, 0xab, 0xda, 0x40,
	0x10, 0xce, 0xaa, 0x2d, 0xb8, 0x42, 0x69, 0x43, 0x0b, 0x31, 0x94, 0x34, 0xd8, 0x4b, 0x4a, 0x61,
	0x83, 0x7a, 0xe9, 0x59, 0x0b, 0x3d, 0x49, 0x21, 0xfd, 0x71, 0xe8, 0xa5, 0xac, 0xc9, 0x34, 0x04,
	0x92, 0xdd, 0x34, 0xbb, 0x8a, 0xfe, 0x17, 0xfd, 0xb3, 0x3c, 0x7a, 0xec, 0xe9, 0xf1, 0xd0, 0x7f,
	0xe0, 0x9d, 0xde, 0xf9, 0x11, 0x93, 0xe8, 0xc3, 0x6c, 0x04, 0xcf, 0xef, 0x36, 0xcc, 0x7c, 0x33,
	0xdf, 0x7c, 0xdf, 0x2e, 0x83, 0x4d, 0x09, 0x49, 0xca, 0x33, 0x1a, 0xbb, 0x3e, 0x4f, 0x52, 0xbe,
	0x60, 0x81, 0x2b, 0x57, 0x24, 0xcd, 0xb8, 0xe4, 0xfa, 0xab, 0xaa, 0x46, 0xaa, 0x9a, 0xe9, 0xd4,
	0xe1, 0x55, 0xf0, 0x5b, 0x80, 0x94, 0x11, 0x0b, 0x8b, 0x66, 0xf3, 0x43, 0x1d, 0xb9, 0xa4, 0x71,
	0x14, 0x50, 0xc9, 0xb3, 0x33, 0xa8, 0xe5, 0x73, 0x91, 0x70, 0xe1, 0xce, 0xa9, 0x00, 0x77, 0x39,
	0x9c, 0x83, 0xa4, 0x43, 0xd7, 0xe7, 0x11, 0x2b, 0xeb, 0xaf, 0x43, 0x1e, 0xf2, 0x43, 0xe8, 0xe6,
	0x51, 0x91, 0x1d, 0xdc, 0x21, 0x6c, 0xcc, 0x44, 0x38, 0xcd, 0x80, 0x4a, 0x98, 0x96, 0x1c, 0xdf,
	0x8a, 0xc1, 0xfa, 0x5b, 0xdc, 0x0d, 0x20, 0x86, 0x30, 0x67, 0x33, 0x90, 0x8d, 0x9c, 0xae, 0x77,
	0x4a, 0xe8, 0x5f, 0xf1, 0xcb, 0xe3, 0x2e, 0x65, 0x87, 0xd1, 0xb2, 0xdb, 0x4e, 0x6f, 0xf4, 0x9e,
	0xd4, 0x34, 0x93, 0x9f, 0x67, 0x50, 0xaf, 0xd6, 0xac, 0x7f, 0xc1, 0x2f, 0x68, 0xc2, 0x17, 0x4c,
	0x7e, 0xe7, 0x1e, 0x24, 0x34, 0x62, 0x46, 0xdb, 0x46, 0x4e, 0x6f, 0xd4, 0x27, 0x85, 0x34, 0x92,
	0x4b, 0x23, 0xa5, 0x34, 0x32, 0xe5, 0x11, 0x9b, 0x74, 0x36, 0x37, 0xef, 0x34, 0xef, 0xac, 0x2d,
	0xdf, 0xfb, 0x4f, 0x06, 0x7f, 0x17, 0xc0, 0xfc, 0xb5, 0xd1, 0xb1, 0x91, 0xf3, 0xcc, 0x3b, 0x25,
	0x06, 0x03, 0x6c, 0x37, 0x29, 0xf6, 0x40, 0xa4, 0x9c, 0x09, 0xa8, 0x6c, 0xf9, 0x91, 0x06, 0x4f,
	0xcc, 0x16, 0xa5, 0xe2, 0xa3, 0x2d, 0x9f, 0x0e, 0xae, 0x7c, 0x86, 0x18, 0xae, 0x74, 0xa5, 0x9c,
	0xae, 0xec, 0xac, 0xa6, 0x8f, 0xee, 0x5b, 0xb8, 0x3d, 0x13, 0xa1, 0xbe, 0xc6, 0x6f, 0xd4, 0xff,
	0xf1, 0xa3, 0xc2, 0xc0, 0xa6, 0xa7, 0x34, 0xc7, 0x57, 0x80, 0xab, 0x15, 0x72, 0x6a, 0xf5, 0x9b,
	0x37, 0x50, 0x2b, 0xc1, 0x4d, 0xd4, 0x17, 0xbd, 0xcd, 0xa9, 0xd5, 0xc6, 0x36, 0x50, 0x2b, 0xc1,
	0x4d, 0xd4, 0x17, 0x8d, 0x9f, 0x8c, 0x37, 0x3b, 0x0b, 0x6d, 0x77, 0x16, 0xba, 0xdd, 0x59, 0xe8,
	0xdf, 0xde, 0xd2, 0xb6, 0x7b, 0x4b, 0xfb, 0xbf, 0xb7, 0xb4, 0x5f, 0xfd, 0xe3, 0xfd, 0x59, 0x3d,
	0x3a, 0x6d, 0xeb, 0x14, 0xc4, 0xfc, 0xf9, 0xe1, 0x80, 0x8c, 0x1f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x39, 0x6b, 0x82, 0x4b, 0xfc, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateCompoundSetting(ctx context.Context, in *MsgCreateCompoundSetting, opts ...grpc.CallOption) (*MsgCreateCompoundSettingResponse, error)
	UpdateCompoundSetting(ctx context.Context, in *MsgUpdateCompoundSetting, opts ...grpc.CallOption) (*MsgUpdateCompoundSettingResponse, error)
	DeleteCompoundSetting(ctx context.Context, in *MsgDeleteCompoundSetting, opts ...grpc.CallOption) (*MsgDeleteCompoundSettingResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateCompoundSetting(ctx context.Context, in *MsgCreateCompoundSetting, opts ...grpc.CallOption) (*MsgCreateCompoundSettingResponse, error) {
	out := new(MsgCreateCompoundSettingResponse)
	err := c.cc.Invoke(ctx, "/temporal.compound.Msg/CreateCompoundSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCompoundSetting(ctx context.Context, in *MsgUpdateCompoundSetting, opts ...grpc.CallOption) (*MsgUpdateCompoundSettingResponse, error) {
	out := new(MsgUpdateCompoundSettingResponse)
	err := c.cc.Invoke(ctx, "/temporal.compound.Msg/UpdateCompoundSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteCompoundSetting(ctx context.Context, in *MsgDeleteCompoundSetting, opts ...grpc.CallOption) (*MsgDeleteCompoundSettingResponse, error) {
	out := new(MsgDeleteCompoundSettingResponse)
	err := c.cc.Invoke(ctx, "/temporal.compound.Msg/DeleteCompoundSetting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateCompoundSetting(context.Context, *MsgCreateCompoundSetting) (*MsgCreateCompoundSettingResponse, error)
	UpdateCompoundSetting(context.Context, *MsgUpdateCompoundSetting) (*MsgUpdateCompoundSettingResponse, error)
	DeleteCompoundSetting(context.Context, *MsgDeleteCompoundSetting) (*MsgDeleteCompoundSettingResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateCompoundSetting(ctx context.Context, req *MsgCreateCompoundSetting) (*MsgCreateCompoundSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCompoundSetting not implemented")
}
func (*UnimplementedMsgServer) UpdateCompoundSetting(ctx context.Context, req *MsgUpdateCompoundSetting) (*MsgUpdateCompoundSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCompoundSetting not implemented")
}
func (*UnimplementedMsgServer) DeleteCompoundSetting(ctx context.Context, req *MsgDeleteCompoundSetting) (*MsgDeleteCompoundSettingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCompoundSetting not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateCompoundSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCompoundSetting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCompoundSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.compound.Msg/CreateCompoundSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCompoundSetting(ctx, req.(*MsgCreateCompoundSetting))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCompoundSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCompoundSetting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCompoundSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.compound.Msg/UpdateCompoundSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCompoundSetting(ctx, req.(*MsgUpdateCompoundSetting))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteCompoundSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteCompoundSetting)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteCompoundSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.compound.Msg/DeleteCompoundSetting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteCompoundSetting(ctx, req.(*MsgDeleteCompoundSetting))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.compound.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompoundSetting",
			Handler:    _Msg_CreateCompoundSetting_Handler,
		},
		{
			MethodName: "UpdateCompoundSetting",
			Handler:    _Msg_UpdateCompoundSetting_Handler,
		},
		{
			MethodName: "DeleteCompoundSetting",
			Handler:    _Msg_DeleteCompoundSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temporal/compound/tx.proto",
}

func (m *MsgCreateCompoundSetting) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCompoundSetting) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCompoundSetting) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Frequency != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Frequency))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.AmountToRemain.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ValidatorSetting) > 0 {
		for iNdEx := len(m.ValidatorSetting) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorSetting[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCompoundSettingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCompoundSettingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCompoundSettingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCompoundSetting) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCompoundSetting) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCompoundSetting) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Frequency != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Frequency))
		i--
		dAtA[i] = 0x20
	}
	{
		size, err := m.AmountToRemain.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.ValidatorSetting) > 0 {
		for iNdEx := len(m.ValidatorSetting) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorSetting[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCompoundSettingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCompoundSettingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCompoundSettingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCompoundSetting) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCompoundSetting) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCompoundSetting) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Delegator) > 0 {
		i -= len(m.Delegator)
		copy(dAtA[i:], m.Delegator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Delegator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCompoundSettingResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCompoundSettingResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCompoundSettingResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateCompoundSetting) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.ValidatorSetting) > 0 {
		for _, e := range m.ValidatorSetting {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = m.AmountToRemain.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.Frequency != 0 {
		n += 1 + sovTx(uint64(m.Frequency))
	}
	return n
}

func (m *MsgCreateCompoundSettingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateCompoundSetting) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.ValidatorSetting) > 0 {
		for _, e := range m.ValidatorSetting {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = m.AmountToRemain.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.Frequency != 0 {
		n += 1 + sovTx(uint64(m.Frequency))
	}
	return n
}

func (m *MsgUpdateCompoundSettingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteCompoundSetting) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Delegator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteCompoundSettingResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateCompoundSetting) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCompoundSetting: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCompoundSetting: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSetting", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorSetting = append(m.ValidatorSetting, &ValidatorSetting{})
			if err := m.ValidatorSetting[len(m.ValidatorSetting)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountToRemain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountToRemain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frequency", wireType)
			}
			m.Frequency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Frequency |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCompoundSettingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCompoundSettingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCompoundSettingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCompoundSetting) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCompoundSetting: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCompoundSetting: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSetting", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorSetting = append(m.ValidatorSetting, &ValidatorSetting{})
			if err := m.ValidatorSetting[len(m.ValidatorSetting)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountToRemain", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountToRemain.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frequency", wireType)
			}
			m.Frequency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Frequency |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCompoundSettingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCompoundSettingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCompoundSettingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCompoundSetting) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCompoundSetting: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCompoundSetting: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Delegator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Delegator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCompoundSettingResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCompoundSettingResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCompoundSettingResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
