// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/record/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetDelegationHistoryRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetDelegationHistoryRequest) Reset()         { *m = QueryGetDelegationHistoryRequest{} }
func (m *QueryGetDelegationHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDelegationHistoryRequest) ProtoMessage()    {}
func (*QueryGetDelegationHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{2}
}
func (m *QueryGetDelegationHistoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDelegationHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDelegationHistoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDelegationHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDelegationHistoryRequest.Merge(m, src)
}
func (m *QueryGetDelegationHistoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDelegationHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDelegationHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDelegationHistoryRequest proto.InternalMessageInfo

func (m *QueryGetDelegationHistoryRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetDelegationHistoryResponse struct {
	DelegationHistory DelegationHistory `protobuf:"bytes,1,opt,name=delegationHistory,proto3" json:"delegationHistory"`
}

func (m *QueryGetDelegationHistoryResponse) Reset()         { *m = QueryGetDelegationHistoryResponse{} }
func (m *QueryGetDelegationHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDelegationHistoryResponse) ProtoMessage()    {}
func (*QueryGetDelegationHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{3}
}
func (m *QueryGetDelegationHistoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDelegationHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDelegationHistoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDelegationHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDelegationHistoryResponse.Merge(m, src)
}
func (m *QueryGetDelegationHistoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDelegationHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDelegationHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDelegationHistoryResponse proto.InternalMessageInfo

func (m *QueryGetDelegationHistoryResponse) GetDelegationHistory() DelegationHistory {
	if m != nil {
		return m.DelegationHistory
	}
	return DelegationHistory{}
}

type QueryAllDelegationHistoryRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDelegationHistoryRequest) Reset()         { *m = QueryAllDelegationHistoryRequest{} }
func (m *QueryAllDelegationHistoryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllDelegationHistoryRequest) ProtoMessage()    {}
func (*QueryAllDelegationHistoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{4}
}
func (m *QueryAllDelegationHistoryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDelegationHistoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDelegationHistoryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDelegationHistoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDelegationHistoryRequest.Merge(m, src)
}
func (m *QueryAllDelegationHistoryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDelegationHistoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDelegationHistoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDelegationHistoryRequest proto.InternalMessageInfo

func (m *QueryAllDelegationHistoryRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllDelegationHistoryResponse struct {
	DelegationHistory []DelegationHistory `protobuf:"bytes,1,rep,name=delegationHistory,proto3" json:"delegationHistory"`
	Pagination        *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllDelegationHistoryResponse) Reset()         { *m = QueryAllDelegationHistoryResponse{} }
func (m *QueryAllDelegationHistoryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllDelegationHistoryResponse) ProtoMessage()    {}
func (*QueryAllDelegationHistoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{5}
}
func (m *QueryAllDelegationHistoryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllDelegationHistoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllDelegationHistoryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllDelegationHistoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllDelegationHistoryResponse.Merge(m, src)
}
func (m *QueryAllDelegationHistoryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllDelegationHistoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllDelegationHistoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllDelegationHistoryResponse proto.InternalMessageInfo

func (m *QueryAllDelegationHistoryResponse) GetDelegationHistory() []DelegationHistory {
	if m != nil {
		return m.DelegationHistory
	}
	return nil
}

func (m *QueryAllDelegationHistoryResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetUserInstructionsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryGetUserInstructionsRequest) Reset()         { *m = QueryGetUserInstructionsRequest{} }
func (m *QueryGetUserInstructionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserInstructionsRequest) ProtoMessage()    {}
func (*QueryGetUserInstructionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{6}
}
func (m *QueryGetUserInstructionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserInstructionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserInstructionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserInstructionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserInstructionsRequest.Merge(m, src)
}
func (m *QueryGetUserInstructionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserInstructionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserInstructionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserInstructionsRequest proto.InternalMessageInfo

func (m *QueryGetUserInstructionsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryGetUserInstructionsResponse struct {
	UserInstructions UserInstructions `protobuf:"bytes,1,opt,name=userInstructions,proto3" json:"userInstructions"`
}

func (m *QueryGetUserInstructionsResponse) Reset()         { *m = QueryGetUserInstructionsResponse{} }
func (m *QueryGetUserInstructionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetUserInstructionsResponse) ProtoMessage()    {}
func (*QueryGetUserInstructionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{7}
}
func (m *QueryGetUserInstructionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetUserInstructionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetUserInstructionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetUserInstructionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetUserInstructionsResponse.Merge(m, src)
}
func (m *QueryGetUserInstructionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetUserInstructionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetUserInstructionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetUserInstructionsResponse proto.InternalMessageInfo

func (m *QueryGetUserInstructionsResponse) GetUserInstructions() UserInstructions {
	if m != nil {
		return m.UserInstructions
	}
	return UserInstructions{}
}

type QueryAllUserInstructionsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllUserInstructionsRequest) Reset()         { *m = QueryAllUserInstructionsRequest{} }
func (m *QueryAllUserInstructionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllUserInstructionsRequest) ProtoMessage()    {}
func (*QueryAllUserInstructionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{8}
}
func (m *QueryAllUserInstructionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllUserInstructionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllUserInstructionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllUserInstructionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllUserInstructionsRequest.Merge(m, src)
}
func (m *QueryAllUserInstructionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllUserInstructionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllUserInstructionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllUserInstructionsRequest proto.InternalMessageInfo

func (m *QueryAllUserInstructionsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllUserInstructionsResponse struct {
	UserInstructions []UserInstructions  `protobuf:"bytes,1,rep,name=userInstructions,proto3" json:"userInstructions"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllUserInstructionsResponse) Reset()         { *m = QueryAllUserInstructionsResponse{} }
func (m *QueryAllUserInstructionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllUserInstructionsResponse) ProtoMessage()    {}
func (*QueryAllUserInstructionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0728550ca9868d5, []int{9}
}
func (m *QueryAllUserInstructionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllUserInstructionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllUserInstructionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllUserInstructionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllUserInstructionsResponse.Merge(m, src)
}
func (m *QueryAllUserInstructionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllUserInstructionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllUserInstructionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllUserInstructionsResponse proto.InternalMessageInfo

func (m *QueryAllUserInstructionsResponse) GetUserInstructions() []UserInstructions {
	if m != nil {
		return m.UserInstructions
	}
	return nil
}

func (m *QueryAllUserInstructionsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "temporal.record.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "temporal.record.QueryParamsResponse")
	proto.RegisterType((*QueryGetDelegationHistoryRequest)(nil), "temporal.record.QueryGetDelegationHistoryRequest")
	proto.RegisterType((*QueryGetDelegationHistoryResponse)(nil), "temporal.record.QueryGetDelegationHistoryResponse")
	proto.RegisterType((*QueryAllDelegationHistoryRequest)(nil), "temporal.record.QueryAllDelegationHistoryRequest")
	proto.RegisterType((*QueryAllDelegationHistoryResponse)(nil), "temporal.record.QueryAllDelegationHistoryResponse")
	proto.RegisterType((*QueryGetUserInstructionsRequest)(nil), "temporal.record.QueryGetUserInstructionsRequest")
	proto.RegisterType((*QueryGetUserInstructionsResponse)(nil), "temporal.record.QueryGetUserInstructionsResponse")
	proto.RegisterType((*QueryAllUserInstructionsRequest)(nil), "temporal.record.QueryAllUserInstructionsRequest")
	proto.RegisterType((*QueryAllUserInstructionsResponse)(nil), "temporal.record.QueryAllUserInstructionsResponse")
}

func init() { proto.RegisterFile("temporal/record/query.proto", fileDescriptor_b0728550ca9868d5) }

var fileDescriptor_b0728550ca9868d5 = []byte{
	// 663 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xb1, 0x6f, 0xd3, 0x4e,
	0x14, 0xc7, 0xe3, 0xf6, 0xf7, 0x0b, 0xe2, 0x18, 0x68, 0xaf, 0x95, 0x5a, 0x0c, 0x72, 0x5a, 0x17,
	0x68, 0x55, 0x54, 0x5f, 0x12, 0x54, 0x09, 0x41, 0x97, 0x44, 0x88, 0x02, 0x62, 0x28, 0x41, 0x30,
	0xb0, 0x54, 0x97, 0xe4, 0xe4, 0x1a, 0xd9, 0x3e, 0xd7, 0x77, 0x06, 0x4a, 0xc5, 0xc2, 0x5f, 0x80,
	0xc4, 0x7f, 0xc1, 0x86, 0xc4, 0xc6, 0xc2, 0xc0, 0xd0, 0xb1, 0x52, 0x17, 0x26, 0x84, 0x12, 0xfe,
	0x10, 0x94, 0xbb, 0x73, 0x93, 0xd8, 0xb1, 0x43, 0xd4, 0x6e, 0x6d, 0xde, 0x7b, 0xdf, 0xfb, 0x7c,
	0xdf, 0xbd, 0x7b, 0x06, 0x57, 0x39, 0xf1, 0x02, 0x1a, 0x62, 0x17, 0x85, 0xa4, 0x45, 0xc3, 0x36,
	0xda, 0x8f, 0x48, 0x78, 0x60, 0x05, 0x21, 0xe5, 0x14, 0x5e, 0x8e, 0x83, 0x96, 0x0c, 0xea, 0xf3,
	0x36, 0xb5, 0xa9, 0x88, 0xa1, 0xde, 0x5f, 0x32, 0x4d, 0xbf, 0x66, 0x53, 0x6a, 0xbb, 0x04, 0xe1,
	0xc0, 0x41, 0xd8, 0xf7, 0x29, 0xc7, 0xdc, 0xa1, 0x3e, 0x53, 0xd1, 0xf5, 0x16, 0x65, 0x1e, 0x65,
	0xa8, 0x89, 0x19, 0x91, 0xea, 0xe8, 0x75, 0xa5, 0x49, 0x38, 0xae, 0xa0, 0x00, 0xdb, 0x8e, 0x2f,
	0x92, 0x63, 0xa5, 0x24, 0x4d, 0x80, 0x43, 0xec, 0xc5, 0x4a, 0x6b, 0xc9, 0x68, 0x9b, 0xb8, 0xc4,
	0x16, 0xf5, 0xbb, 0x7b, 0x0e, 0xe3, 0x34, 0x06, 0xd7, 0xd7, 0x73, 0x32, 0xb9, 0xe3, 0x11, 0xc6,
	0xb1, 0x17, 0xa8, 0xdc, 0xd5, 0x64, 0x6e, 0xc4, 0x48, 0xb8, 0xeb, 0xf8, 0x8c, 0x87, 0x51, 0x6b,
	0xc0, 0x88, 0x39, 0x0f, 0xe0, 0xd3, 0x1e, 0xfe, 0x8e, 0x60, 0x6a, 0x90, 0xfd, 0x88, 0x30, 0x6e,
	0x3e, 0x01, 0x73, 0x43, 0xbf, 0xb2, 0x80, 0xfa, 0x8c, 0xc0, 0x4d, 0x50, 0x94, 0xec, 0x8b, 0xda,
	0x92, 0xb6, 0x76, 0xa9, 0xba, 0x60, 0x25, 0x7a, 0x69, 0xc9, 0x82, 0xfa, 0x7f, 0x47, 0xbf, 0x4a,
	0x85, 0x86, 0x4a, 0x36, 0xb7, 0xc0, 0x92, 0x50, 0xdb, 0x26, 0xfc, 0xfe, 0x29, 0xf2, 0x43, 0xe9,
	0x4d, 0x9d, 0x08, 0x17, 0xc1, 0x05, 0xdc, 0x6e, 0x87, 0x84, 0x49, 0xed, 0x8b, 0x8d, 0xf8, 0x5f,
	0xf3, 0x10, 0x2c, 0xe7, 0x54, 0x2b, 0xb2, 0x17, 0x60, 0xb6, 0x9d, 0x0c, 0x2a, 0x48, 0x33, 0x05,
	0x99, 0x92, 0x51, 0xbc, 0x69, 0x09, 0xf3, 0x95, 0x42, 0xaf, 0xb9, 0x6e, 0x26, 0xfa, 0x03, 0x00,
	0xfa, 0x77, 0xae, 0x0e, 0xbd, 0x69, 0xc9, 0x01, 0xb1, 0x7a, 0x03, 0x62, 0xc9, 0xf1, 0x53, 0x03,
	0x62, 0xed, 0x60, 0x9b, 0xa8, 0xda, 0xc6, 0x40, 0xa5, 0xf9, 0x43, 0x53, 0x4e, 0x47, 0x1f, 0x96,
	0xef, 0x74, 0xfa, 0x8c, 0x4e, 0xe1, 0xf6, 0x90, 0x8b, 0x29, 0xe1, 0x62, 0x75, 0xac, 0x0b, 0x09,
	0x35, 0x64, 0xe3, 0x1e, 0x28, 0xc5, 0xf7, 0xf5, 0x9c, 0x91, 0xf0, 0xd1, 0xc0, 0xcc, 0x8d, 0xbf,
	0xec, 0x37, 0xfd, 0x51, 0x49, 0x17, 0xab, 0x0e, 0x3c, 0x03, 0x33, 0x51, 0x22, 0xa6, 0xba, 0xbe,
	0x9c, 0x6a, 0x40, 0x52, 0x44, 0xf9, 0x4f, 0x09, 0x98, 0x8e, 0xa2, 0xae, 0xb9, 0x6e, 0x16, 0xf5,
	0x79, 0xdd, 0xf3, 0x77, 0xad, 0x3f, 0x54, 0x13, 0x9a, 0x9c, 0x3e, 0x93, 0xc9, 0x73, 0xbb, 0xe3,
	0xea, 0x49, 0x11, 0xfc, 0x2f, 0x2c, 0x40, 0x0e, 0x8a, 0xf2, 0xcd, 0xc3, 0x95, 0x14, 0x57, 0x7a,
	0xb1, 0xe8, 0xd7, 0xf3, 0x93, 0xe4, 0x51, 0x66, 0xe9, 0xc3, 0xc9, 0x9f, 0x4f, 0x53, 0x57, 0xe0,
	0x02, 0x1a, 0xbd, 0x3a, 0xe1, 0x17, 0x0d, 0xcc, 0xa6, 0x66, 0x1b, 0x56, 0x46, 0x8b, 0xe7, 0xac,
	0x1d, 0xbd, 0x3a, 0x49, 0x89, 0xa2, 0xdb, 0x14, 0x74, 0x08, 0x6e, 0xa0, 0xf1, 0xab, 0x1b, 0x1d,
	0xaa, 0xc9, 0x7e, 0x0f, 0x3f, 0x6b, 0x60, 0x3e, 0x25, 0x5a, 0x73, 0xdd, 0x2c, 0xec, 0x9c, 0x95,
	0x93, 0x85, 0x9d, 0xb7, 0x38, 0xcc, 0x5b, 0x02, 0xfb, 0x06, 0x5c, 0xf9, 0x07, 0x6c, 0xf8, 0x4d,
	0x03, 0x33, 0xc9, 0xb1, 0x82, 0xe5, 0xcc, 0x66, 0x65, 0x3c, 0x19, 0xbd, 0x32, 0x41, 0x85, 0xc2,
	0xac, 0x0b, 0xcc, 0x2d, 0x78, 0xf7, 0x14, 0x73, 0xe3, 0x1d, 0xf5, 0x09, 0x1a, 0xfb, 0x41, 0x1b,
	0x68, 0xf5, 0x57, 0x0d, 0xcc, 0x25, 0x0f, 0xe8, 0x75, 0xba, 0x9c, 0xd9, 0xb6, 0x09, 0x0d, 0xe4,
	0xbc, 0x5c, 0xf3, 0x8e, 0x30, 0x50, 0x85, 0xe5, 0x49, 0x0d, 0xd4, 0x1f, 0x1f, 0x75, 0x0c, 0xed,
	0xb8, 0x63, 0x68, 0xbf, 0x3b, 0x86, 0xf6, 0xb1, 0x6b, 0x14, 0x8e, 0xbb, 0x46, 0xe1, 0x67, 0xd7,
	0x28, 0xbc, 0x2c, 0xdb, 0x0e, 0xdf, 0x8b, 0x9a, 0x56, 0x8b, 0x7a, 0x59, 0xaa, 0x6f, 0x63, 0x5d,
	0x7e, 0x10, 0x10, 0xd6, 0x2c, 0x8a, 0xcf, 0xfb, 0xed, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x54,
	0x0d, 0x0a, 0x84, 0x0b, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of DelegationHistory items.
	DelegationHistory(ctx context.Context, in *QueryGetDelegationHistoryRequest, opts ...grpc.CallOption) (*QueryGetDelegationHistoryResponse, error)
	DelegationHistoryAll(ctx context.Context, in *QueryAllDelegationHistoryRequest, opts ...grpc.CallOption) (*QueryAllDelegationHistoryResponse, error)
	// Queries a list of UserInstructions items.
	UserInstructions(ctx context.Context, in *QueryGetUserInstructionsRequest, opts ...grpc.CallOption) (*QueryGetUserInstructionsResponse, error)
	UserInstructionsAll(ctx context.Context, in *QueryAllUserInstructionsRequest, opts ...grpc.CallOption) (*QueryAllUserInstructionsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/temporal.record.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DelegationHistory(ctx context.Context, in *QueryGetDelegationHistoryRequest, opts ...grpc.CallOption) (*QueryGetDelegationHistoryResponse, error) {
	out := new(QueryGetDelegationHistoryResponse)
	err := c.cc.Invoke(ctx, "/temporal.record.Query/DelegationHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DelegationHistoryAll(ctx context.Context, in *QueryAllDelegationHistoryRequest, opts ...grpc.CallOption) (*QueryAllDelegationHistoryResponse, error) {
	out := new(QueryAllDelegationHistoryResponse)
	err := c.cc.Invoke(ctx, "/temporal.record.Query/DelegationHistoryAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserInstructions(ctx context.Context, in *QueryGetUserInstructionsRequest, opts ...grpc.CallOption) (*QueryGetUserInstructionsResponse, error) {
	out := new(QueryGetUserInstructionsResponse)
	err := c.cc.Invoke(ctx, "/temporal.record.Query/UserInstructions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserInstructionsAll(ctx context.Context, in *QueryAllUserInstructionsRequest, opts ...grpc.CallOption) (*QueryAllUserInstructionsResponse, error) {
	out := new(QueryAllUserInstructionsResponse)
	err := c.cc.Invoke(ctx, "/temporal.record.Query/UserInstructionsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of DelegationHistory items.
	DelegationHistory(context.Context, *QueryGetDelegationHistoryRequest) (*QueryGetDelegationHistoryResponse, error)
	DelegationHistoryAll(context.Context, *QueryAllDelegationHistoryRequest) (*QueryAllDelegationHistoryResponse, error)
	// Queries a list of UserInstructions items.
	UserInstructions(context.Context, *QueryGetUserInstructionsRequest) (*QueryGetUserInstructionsResponse, error)
	UserInstructionsAll(context.Context, *QueryAllUserInstructionsRequest) (*QueryAllUserInstructionsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) DelegationHistory(ctx context.Context, req *QueryGetDelegationHistoryRequest) (*QueryGetDelegationHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegationHistory not implemented")
}
func (*UnimplementedQueryServer) DelegationHistoryAll(ctx context.Context, req *QueryAllDelegationHistoryRequest) (*QueryAllDelegationHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegationHistoryAll not implemented")
}
func (*UnimplementedQueryServer) UserInstructions(ctx context.Context, req *QueryGetUserInstructionsRequest) (*QueryGetUserInstructionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInstructions not implemented")
}
func (*UnimplementedQueryServer) UserInstructionsAll(ctx context.Context, req *QueryAllUserInstructionsRequest) (*QueryAllUserInstructionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserInstructionsAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.record.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DelegationHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDelegationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegationHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.record.Query/DelegationHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegationHistory(ctx, req.(*QueryGetDelegationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DelegationHistoryAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllDelegationHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegationHistoryAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.record.Query/DelegationHistoryAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegationHistoryAll(ctx, req.(*QueryAllDelegationHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserInstructions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetUserInstructionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserInstructions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.record.Query/UserInstructions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserInstructions(ctx, req.(*QueryGetUserInstructionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserInstructionsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllUserInstructionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserInstructionsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.record.Query/UserInstructionsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserInstructionsAll(ctx, req.(*QueryAllUserInstructionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.record.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DelegationHistory",
			Handler:    _Query_DelegationHistory_Handler,
		},
		{
			MethodName: "DelegationHistoryAll",
			Handler:    _Query_DelegationHistoryAll_Handler,
		},
		{
			MethodName: "UserInstructions",
			Handler:    _Query_UserInstructions_Handler,
		},
		{
			MethodName: "UserInstructionsAll",
			Handler:    _Query_UserInstructionsAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temporal/record/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetDelegationHistoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDelegationHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDelegationHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDelegationHistoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDelegationHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDelegationHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DelegationHistory.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllDelegationHistoryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDelegationHistoryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDelegationHistoryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllDelegationHistoryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllDelegationHistoryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllDelegationHistoryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.DelegationHistory) > 0 {
		for iNdEx := len(m.DelegationHistory) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DelegationHistory[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserInstructionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserInstructionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserInstructionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetUserInstructionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetUserInstructionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetUserInstructionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.UserInstructions.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllUserInstructionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllUserInstructionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllUserInstructionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllUserInstructionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllUserInstructionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllUserInstructionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserInstructions) > 0 {
		for iNdEx := len(m.UserInstructions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.UserInstructions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetDelegationHistoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDelegationHistoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DelegationHistory.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllDelegationHistoryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllDelegationHistoryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DelegationHistory) > 0 {
		for _, e := range m.DelegationHistory {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUserInstructionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetUserInstructionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.UserInstructions.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllUserInstructionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllUserInstructionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.UserInstructions) > 0 {
		for _, e := range m.UserInstructions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDelegationHistoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDelegationHistoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDelegationHistoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDelegationHistoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDelegationHistoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDelegationHistoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelegationHistory.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDelegationHistoryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDelegationHistoryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDelegationHistoryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllDelegationHistoryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllDelegationHistoryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllDelegationHistoryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelegationHistory", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DelegationHistory = append(m.DelegationHistory, DelegationHistory{})
			if err := m.DelegationHistory[len(m.DelegationHistory)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserInstructionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserInstructionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserInstructionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetUserInstructionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetUserInstructionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetUserInstructionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserInstructions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UserInstructions.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllUserInstructionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllUserInstructionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllUserInstructionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllUserInstructionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllUserInstructionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllUserInstructionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserInstructions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserInstructions = append(m.UserInstructions, UserInstructions{})
			if err := m.UserInstructions[len(m.UserInstructions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
